helmVersion: 0.1.3 # Define the version of the superstream helm chart.
environmentName: <YOUR_ENV_NAME> # "Define the environment name within 32 characters, excluding '.', and using only letters, numbers, '-', and '_.'"
namespace: superstream # Specify the Kubernetes namespace where the resources will be deployed, isolating them within this designated namespace.
accountId: "" # Provide the account ID that is associated with the deployment, which could be used for identifying resources or configurations tied to a specific account.
activationToken: "" # Enter the activation token required for services or resources that need an initial token for activation or authentication.
loggingToken: ""
monitoringToken: ""
