repositories:
    - name: nats 
      url: https://nats-io.github.io/k8s/helm/charts/

environments:
  default:
    values:
    - ../environments/default.yaml

---
releases:
  - name: {{ .Values.natsReleaseName }}
    installed: true
    namespace: {{ .Values.namespace }}
    chart: nats/nats
    version: 1.1.10
    values:
      - container:
          env: 
            ACTIVATION_TOKEN:
              valueFrom:
                secretKeyRef:
                  name: superstream-creds
                  key: ACTIVATION_TOKEN 
      - promExporter:
          enabled: true
      - natsBox:
          enabled: false  
      - config:
            cluster: 
              enabled: {{ .Values.haDeployment }}
            jetstream: 
              enabled: true
            merge: { 
                            accounts: {
                              SYS: {
                                users: [{user: superstream_sys, password: << $ACTIVATION_TOKEN >>}]
                                # System account allows subscribing to $SYS.>
                              },
                              internal: {
                                jetstream: enable,
                                users: [{user: superstream_internal, password: << $ACTIVATION_TOKEN >>}]
                                # Regular user account for clients
                              }
                            },
                            # Reference the system account
                            "system_account": SYS,
                            "remote_syslog": "udp://{{ .Values.superstreamReleaseName }}-syslog.{{ .Values.namespace }}:5514",
                            "max_payload":  << 8MB >>
            }