repositories:
    - name: superstream 
      url: https://k8s.superstream.dev/charts/

environments:
  default:
    values:
    - ../environments/default.yaml

helmDefaults:
  wait: true

---
releases:
  - name: {{ .Values.superstreamReleaseName }} 
    installed: true
    namespace: {{ .Values.namespace }}
    chart: superstream/superstream
    version: {{ .Values.helmVersion }}
    values:
      - ../config.yaml
      - superstream:
          environment: {{ .Values.name }}
      - dataPlane:
          secret:
            activationToken: {{ .Values.activationToken }}
          resources:
            requests:
              cpu: {{ .Values.requestCpu }}
              memory: {{ .Values.requestMemory }}
          controlPlane:
            host: {{ .Values.controlPlane }}
          internalNatsConnection:
            host: {{ .Values.natsReleaseName }}
          releaseDate: {{ .Values.releaseDate }} 
